name: Tests Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the specified branch
  push:
    branches:
     - "main"
  pull_request:
    branches:
     - "main"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  AIND_Fusion-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    container: lironavon/docker-puppeteer-container:14.16.0
    env:
      CI: true
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: tests/package-lock.json
    - name: AIND Fusion Regression test
      run: |
          cd tests
          #install dependencies
          npm ci
          # run test
          npm test aind_fusion_regression
      env:
          CI: true
  